### ISSUE TITLE
SignPath signing step fails: Cannot deserialize JSON from GitHub API to WorkflowRunJobsDto

### ISSUE THREAD

**Issue by synacker** [SignPath/github-actions#39]
**Describe the bug**

The GitHub Actions workflow fails at the SignPath signing step. The error message is:

```
JSON received from GitHub API cannot be deserialized to WorkflowRunJobsDto.
```

This occurs during the step: "Submitting the signing request to SignPath CI connector". No custom code in the repository appears to use `WorkflowRunJobsDto`, so the error is likely from the `signpath/github-action-submit-signing-request@v1.1` action or a related library.

**To Reproduce**
1. Trigger a workflow run that reaches the signing step (e.g., by opening a pull request that builds successfully).
2. Observe the workflow logs after the build/tests complete.
3. The signing step fails with the above error.

**Expected behavior**
The signing step should complete successfully and produce signed artifacts.

**Desktop (please complete the following information):**
- OS: GitHub Actions (Windows runner)

**Additional context**
- See [SignPath composite action](https://github.com/synacker/daggy/blob/d1f7bca47c42890dfe040b3c59bc9ee03824f172/.github/actions/sign/action.yaml) setup in this repository.
- [The error](https://github.com/synacker/daggy/actions/runs/15237958022/job/42854358743#step:9:134) appears to originate from the third-party SignPath GitHub Action or the SignPath service itself.

**Workflow Log Snippet**
```
2025-05-25T12:05:31.8986699Z Submitting the signing request to SignPath CI connector...
2025-05-25T12:05:33.9755981Z ##[error]JSON received from GitHub API cannot be deserialized to WorkflowRunJobsDto. ({"total_count":20,"jobs":[{"id":42853599574,...
```

**Comment by synacker** [comment]
The first error occurence [were at 22.05.2025](https://github.com/synacker/daggy/actions/runs/15197912945/job/42746628619#step:6:133).

I didn't change sign action. Last success workflow with test-signing policy [were at 18.05.2025](https://github.com/synacker/daggy/actions/runs/15096659070/job/42432235440#step:6:145).

**Comment by paulsavoie** [comment]
Hello @synacker , thank you for notifying us.
We deployed a new release of the GitHub Actions integration on Thursday that fixes a bug in how we ensure that all jobs are executed on GitHub-hosted runners. We aligned with the GitHub support team on how that's expressed in the API response, but it seems that in your case, the API returns something unexpected (`runner_group_id` and `_name` being `null`).

I've reached out to GitHub again and hope to get an answer soon so that we can provide a fix. In the meantime, we will try to reproduce the issue on our side, as all our tests (and the builds of other OSS projects) are green.

**Comment by synacker** [comment]
Thank you for answer!

I think, that the main problem in JSON that breaking at end. Therefore, github workflow can't parse it.

**Comment by sunshowers** [comment]
Thanks for filing the issue. I'm also seeing this at https://github.com/nextest-rs/nextest/actions/runs/15262653934/job/42925225045.

Running

```
% gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
/repos/nextest-rs/nextest/actions/runs/15262653934/jobs
```

I can see that `runner_group_id` is indeed null.

Looking at an earlier commit that worked:

```
% gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
/repos/nextest-rs/nextest/actions/runs/15111623277/jobs
```

I do see that `runner_group_id` is always 0 and `runner_group_name` is GitHub Actions.

**Comment by sunshowers** [comment]
FWIW I see that the schema at https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#list-jobs-for-a-workflow-run-attempt has:

```
          "runner_group_id": {
            "type": [
              "integer",
              "null"
            ],
            "description": "The ID of the runner group to which this job has been assigned. (If a runner hasn't yet been assigned, this will be null.)",
            "examples": [
              2
            ]
          },
          "runner_group_name": {
            "type": [
              "string",
              "null"
            ],
            "description": "The name of the runner group to which this job has been assigned. (If a runner hasn't yet been assigned, this will be null.)",
            "examples": [
              "my runner group"
            ]
```

So it looks like it can be null for jobs where "a runner hasn't yet been assigned". That appears to include skipped jobs, where a runner will never be assigned. ("yet" is quite misleading there!)

In my case, I had two attempts.

1. For attempt 1 ([web URL](https://github.com/nextest-rs/nextest/actions/runs/15262653934/job/42923123398), [JSON output](https://gist.github.com/sunshowers/b8b8675ca078f7af78555d931f304ff0)) there are several jobs which were skipped because they weren't part of this release. This is as expected -- you can see the skipped jobs at the web URL. For those jobs, the runner group ID is null.
2. For attempt 2 ([web URL](https://github.com/nextest-rs/nextest/actions/runs/15262653934/job/42925225045), [JSON output](https://gist.github.com/sunshowers/5bb5d15ad1b30a74ae61b52e403f69bb)), I hit "retry failed jobs" which caused the successful jobs to be skipped. For those jobs the runner group ID is null as well.

I presume you need to check the runner group ID to make sure that the binary is being built on hosted GitHub Actions. I think an appropriate fix here would be to accept null for jobs in general, but require that it is set for the jobs you're interested in. In this case, the Windows binary building jobs [do have the runner group set](https://gist.github.com/sunshowers/5bb5d15ad1b30a74ae61b52e403f69bb#file-gistfile0-txt-L282-L283)).

edit: Looking at the earlier, successful job using the test-signing key ([JSON output](https://gist.github.com/sunshowers/212dc606c8a15f9af34e2feab486769a)) I see that `runner_group_id` is set to null for the skipped jobs as well, so it doesn't seem like a recent change on GitHub's end.

**Comment by paulsavoie** [comment]
Thanks for the input!

To clarify: GitHub had a change and then supposedly changed it back

@sunshowers: You are correct that no `runner_group_id` and `runner_group_name` is set for skipped jobs. We actually detect those, maybe there's a bug in our implementation. You can see those in your samples in the `"conclusion": "skipped"`.

For the original issue, however, there are some jobs that were not skipped, but executed properly and still have no group id and group name. I've already created a support request with GitHub and they're looking into it.

**Comment by paulsavoie** [comment]
Update: We were able to verify that for skipped jobs, this is actually a bug on our side, the runner for these jobs of the previous attempts should be considered. We're working on a fix.

For now, please select "Re-run all jobs" when retrying a workflow run.

Of course, this does not solve the original problem when the response from GitHub is incomplete.

**Comment by synacker** [comment]
@paulsavoie I did "re-run all jobs", but result is the same

https://github.com/synacker/daggy/actions/runs/15240224629/job/42968362066

**Comment by paulsavoie** [comment]
Hello @synacker, sorry, should have mentioned @sunshowers - their problem should be resolved with a re-run. Yours is unfortunately a different one - I'm still waiting for a response from GitHub on how to proceed with it.

**Comment by synacker** [comment]
@paulsavoie okey, I'm not correctly understood you before, thank you for clarification.

**Comment by sunshowers** [comment]
@paulsavoie thanks, appreciate the quick turnaround! Unfortunately I'm still seeing the issue with a brand new release with [just one attempt](https://github.com/nextest-rs/nextest/actions/runs/15282520978/job/42984802361). Here's the [JSON output](https://gist.github.com/sunshowers/f5cf798aa78360b363dda3f9d4899369).

Looking at for example [lines 97-121](https://gist.github.com/sunshowers/f5cf798aa78360b363dda3f9d4899369#file-gistfile0-txt-L97-L121), the `nextest-runner-release` job is skipped. That corresponds to [this line in the workflow file](https://github.com/nextest-rs/nextest/actions/runs/15282520978/workflow#L61) which skips the job if the tag name doesn't match. The tag name that I pushed is `cargo-nextest-0.9.97-rc.2`.

**Comment by sunshowers** [comment]
Hmm, I guess I could move out just the cargo-nextest-release set of jobs into its own workflow file

**Comment by synacker** [comment]
Is separate workflow without skipped jobs will workaround of the problem?

**Comment by synacker** [comment]
I moved signing to the separate workflow without skipped jobs, but the result is [the same](https://github.com/synacker/daggy/actions/runs/15335140672/job/43150728645#step:9:134).

**Comment by sunshowers** [comment]
@synacker ah there seems to be something else going on in your case -- seems like your workflow has some [pseudo-jobs](https://github.com/synacker/daggy/actions/runs/15335140672/job/43150802112) that map to null ([JSON output](https://gist.github.com/sunshowers/38da2fb48b4bf7ac1663e1cabf80823a#file-gistfile0-txt-L264-L267)). Are those jobs of yours being created by something special?

**Comment by sunshowers** [comment]
ahh looks like those are from https://github.com/mikepenz/action-junit-report -- it publishes test results as PR checks (which will end up with a null runner).

**Comment by synacker** [comment]
@sunshowers thank you for answer! This is not a pseudo-jobs. This is a results of the another workflow for same commit: https://github.com/synacker/daggy/actions/runs/15335173437 I have no idea, why they migrated to the non-relative workflow. It looks like a bug with github actions.

**Comment by synacker** [comment]
I found a workaround. I [moved](https://github.com/synacker/daggy/actions/runs/15380205493/job/43269921897) the signing build to the separate dispatched workflow (it runs manually) without skipped job.

**Comment by paulsavoie** [comment]
Hello @synacker and @sunshowers, sorry for the delayed response. We have analyzed the issue now (took us a while because it was shadowed by another, unrelated GitHub bug). We are working on a fix and will release an update next week. Sorry for the incovenience.

The bug is caused by us incorrectly handling skipped/or queued jobs (that don't have a runner assigned). If you have urgent needs to get a release out, please reach out to oss-support@signpath.org.

**Comment by synacker** [comment]
@paulsavoie thank you for answer! As I said before, I found a workaround solution with separate build without skipped jobs and already sign my last release. It works nice for me and looks better, than my previous solution. But, I'm glad to here, that my issue report was help you catch and resolve bug!

**Comment by sunshowers** [comment]
Thanks @paulsavoie — happy to wait for now. Looking forward to the fix!

**Comment by paulsavoie** [comment]
Hello @sunshowers and @synacker: I just wanted to let you know that we released an update today that fixes this issue. I am going to close it accordingly. Please let me know if any problems persist.
